[package]
name = "acme"
version = "0.1.0"
edition = "2018"
license = "Apache-2.0"
description = "Async pure-Rust ACME client"
homepage = "https://github.com/InstantDomain/instant-acme"
repository = "https://github.com/InstantDomain/instant-acme"
documentation = "https://docs.rs/instant-acme"
keywords = ["letsencrypt", "acme"]
categories = ["web-programming", "api-bindings"]

[dependencies]
base64 = "0.13.0"
hyper = { version = "0.14.18", features = ["client", "http1", "http2"] }
hyper-rustls = { version = "0.23.0", default-features = false, features = ["http1", "http2", "native-tokio", "tls12"] }
ring = { version = "0.16.20", features = ["std"] }
serde = { version = "1.0.104", features = ["derive"] }
serde_json = "1.0.78"
thiserror = "1.0.30"
